### ISSUE TITLE
Connecting to PostGIS without password vs. "trust"-based authentication

### ISSUE THREAD

**Issue by ohobby** [earthobservations/luftdatenpumpe#45]
Hi,

something are changes at postgres (or at debian 11 where i try to install the luftdatenpumpe), it is not possible to use the user luftdatenpumpe without password for the import.

https://github.com/earthobservations/luftdatenpumpe/blob/main/doc/setup/ldview-databases.rst

Regards,
Oliver

**Comment by amotl** [comment]
Hi Oliver,

thank you for reporting this. Can you describe at which command an error is happening, and what the error output is?

Are you able to connect to PostgreSQL using this command, maybe after running `su - postgres`?
```
psql -U luftdatenpumpe -h localhost -d weatherbase
```

Note that, I've just removed the following section from the documentation. Maybe it was important, and should be brought back?
> Sometimes, for example when working with Docker, adding options where PostGIS can be found, is sensible. Example:
> ```
> export PGHOST=localhost
> export PGUSER=postgres
> ```

With kind regards,
Andreas.

**Comment by amotl** [comment]
Please note that we've configured our PostgreSQL instance to trust connections from `localhost`, and other local connections, to ease accessibility in testing and sandbox situations, and probably also on the server.

- https://github.com/earthobservations/luftdatenpumpe/blob/621e67c7bb220a0543db7f63e58df3fe4a3383ea/Makefile#L123
- https://github.com/earthobservations/luftdatenpumpe/blob/0.21.1/doc/setup/postgresql.rst

Please recognize that this may weaken the security a bit, so we are also happy to hear about any suggestions for improvements in this area. We will be happy to receive corresponding patches to the code base or documentation.

Relating to this directive within the [Luftdaten-Viewer Databases] documentation, ...
```sql
CREATE ROLE luftdatenpumpe WITH LOGIN;
```
... it should be possible to specify a password there, by using such a directive instead:
```sql
CREATE ROLE luftdatenpumpe WITH LOGIN PASSWORD 'YOUR_SECRET_PASSWORD';
```
... and then use the connection URI `postgresql://luftdatenpumpe:YOUR_SECRET_PASSWORD@localhost/weatherbase` in subsequent steps. Please let us know if you think adjusting the documentation correspondingly would be an improvement on this matter.

[Luftdaten-Viewer Databases]: https://github.com/earthobservations/luftdatenpumpe/blob/0.21.1/doc/setup/ldview-databases.rst

**Comment by ohobby** [comment]
Hi Andreas,

i have now also trust the localhost connections.
I open this issue, for possible clarified this in the documentation for other new users.

Thanks,
Oliver

**Comment by amotl** [comment]
Hi Oliver,

documentation on this matter will be improved with ae715990d93. Let me know, and eventually re-open, if you think this issue needs further actions.

With kind regards,
Andreas.
